In [1]:
import numpy as np
Resources_Matrix = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

Allocation_Factors = np.array([
    [1, 0.5],
    [0.2, 1]
])
Result = Resources_Matrix @ Allocation_Factors
print(Result)


Shift_A_Production = np.array([
    [5, 6, 7, 8, 9, 10, 11],
    [4, 5, 6, 7, 8, 9, 10],
    [3, 4, 5, 6, 7, 8, 9]
])

Shift_B_Production = np.array([
    [2, 3, 4, 5, 6, 7, 8],
    [1, 2, 3, 4, 5, 6, 7],
    [0, 1, 2, 3, 4, 5, 6]
])
Total_Production = Shift_A_Production + Shift_B_Production
print(Total_Production)


def sigmoid(x):
    return 1 / (1 + np.exp(-x))
test_values = np.array([-2, -1, 0, 1, 2])
print(sigmoid(test_values))


def sigmoid_gradient(x):
    s = sigmoid(x)
    return s * (1 - s)
print(sigmoid_gradient(test_values))


import numpy as np
X = np.array([
    [20, 3, 4],
    [15, 5, 3],
    [30, 2, 2],
    [25, 4, 1],
    [35, 2, 3]
], dtype=float)

y = np.array([[18], [20], [22], [25], [30]], dtype=float)

X = X / X.max(axis=0)
y = y / y.max()

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

np.random.seed(1)

W1 = np.random.rand(3, 3)
b1 = np.zeros((1, 3))

W2 = np.random.rand(3, 1)
b2 = np.zeros((1, 1))

learning_rate = 0.1
epochs = 2000
losses = []

for _ in range(epochs):

    z1 = X @ W1 + b1
    a1 = relu(z1)

    z2 = a1 @ W2 + b2
    y_pred = sigmoid(z2)

    loss = np.mean((y - y_pred) ** 2)
    losses.append(loss)

    d_loss_y = 2 * (y_pred - y) / len(y)
    d_y_z2 = sigmoid_derivative(z2)

    d_z2 = d_loss_y * d_y_z2
    d_W2 = a1.T @ d_z2
    d_b2 = np.sum(d_z2, axis=0, keepdims=True)

    d_a1 = d_z2 @ W2.T
    d_z1 = d_a1 * relu_derivative(z1)

    d_W1 = X.T @ d_z1
    d_b1 = np.sum(d_z1, axis=0, keepdims=True)

    W2 -= learning_rate * d_W2
    b2 -= learning_rate * d_b2
    W1 -= learning_rate * d_W1
    b1 -= learning_rate * d_b1

print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

print("\nПредсказания:")
print(y_pred)

[[14. 25.]
 [38. 55.]
 [62. 85.]]
[[ 7  9 11 13 15 17 19]
 [ 5  7  9 11 13 15 17]
 [ 3  5  7  9 11 13 15]]
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]
[0.10499359 0.19661193 0.25       0.19661193 0.10499359]
W1:
 [[ 0.91613606  1.18107821  0.47457748]
 [ 0.1865404   0.04147087 -0.02770444]
 [-0.35660515 -0.16506875 -0.09499464]]
b1:
 [[-0.06918318 -0.07125819 -0.04603201]]
W2:
 [[0.9980505 ]
 [0.97200023]
 [0.73506143]]
b2:
 [[-0.06990872]]

Предсказания:
[[0.66226197]
 [0.63595116]
 [0.83395885]
 [0.81733445]
 [0.85958771]]
